export const FECH_BLOCKCHAIN = 'FECH_BLOCKCHAIN';
export const UPDATE_BLOCKCHAIN_DATA_FIND = 'UPDATE_BLOCKCHAIN_DATA_FIND';
export const ADD_BLOCKCHAIN_DATA = 'ADD_BLOCKCHAIN_DATA';
export const FECH_BLOCKCHAIN_BLOCK_NUMBER = 'FECH_BLOCKCHAIN_BLOCK_NUMBER';
export const UPDATE_BLOCKCHAIN_DATA = 'UPDATE_BLOCKCHAIN_DATA';
export const CreateBlockchain = 'CreateBlockchain';
export const GET_UPDATED ='GET_UPDATED';